import Sidebar from "../Sidebar/Sidebar";

import { Inter } from "next/font/google";
import styles from "./Layout.module.scss";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Clerkie Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.layout} ${inter.className}`}>
        <Sidebar />
        <main>{children}</main>
      </div>
    </>
  );
}
